Iv Cipher
oreshinya/purescript-crypto pull request #10
Opened 2021-06-15 16:04 UTC by hivemind-julius

Hey 👋 ,

this will interface to the `crypto.createCipheriv` and `crypto.createDecipheriv` of the underlying node crypto library. It references the issue mentioned in #9.

We are already using it in an internal project and I am looking forward to discuss changes needed in order to merge it.

2021-07-04 13:10 UTC, oreshinya requested changes

2021-07-04 13:10 UTC, oreshinya commented on src/Node/Crypto/Types.purs
> +  = InitializationVector String
`Some types can be used as `iv`.
At least newtype is not suitable.

I think better that you want to use `data` or typeclass and instantiate `String`.

2021-08-03 09:37 UTC, hivemind-julius commented on src/Node/Crypto/Types.purs
> +  = Plaintext String
I personally like to really separate the input and output types, but I am fine with changing it to type aliases so that we have Strings here ;-)

2021-08-05 14:28 UTC, hivemind-julius commented on src/Node/Crypto/Hmac.purs
> +newtype Secret = Secret String
I renamed it to `Key`, since the official documentation of the node module uses the term, too.

2021-08-05 14:56 UTC, hivemind-julius commented
Hey @oreshinya ,

thanks for the feedback. I changed the pr according to your requests ;-)

In my opinion, the interface should be changed in the future to support more than just `Strings` and change the typo of e.g. the `Key` to be a data type and hence, also support `Buffer` and so forth (see e.g. [createCipherIv](https://nodejs.org/dist/latest-v16.x/docs/api/crypto.html#crypto_crypto_createcipheriv_algorithm_key_iv_options)).

Further more, Algorithm should be changed to reflect the different combinations regarding `Initialization Vector` and `Authentication` (the latter ones do have an auth tag).

However, these are things to consider in the future and when needed ;-)

I hope the pr does satisfy you now :-)

Looking forward to hear from you!

Kind regards

2021-09-27 04:53 UTC, closed without merging